CREATE TABLE IF NOT EXISTS salon
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre      VARCHAR(60)                             NOT NULL,
    capacidad   INT,
    descripcion VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_salon PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS evento
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre    VARCHAR(60)                             NOT NULL,
    fecha     date,
    invitados INT,
    salon_id  BIGINT,
    CONSTRAINT pk_evento PRIMARY KEY (id)
);


ALTER TABLE evento
    ADD CONSTRAINT FK_EVENTO_ON_SALON FOREIGN KEY (salon_id) REFERENCES salon (id);